### PR TITLE
Fixed crash when using non-main thread to call SwiftUI

### PR DESCRIPTION
**Pull request by azisramdhan**
# Description
This PR contains bug fixes for:
 

##  Litewallet internal issues
- [14](https://github.com/litecoin-foundation/litewallet-engineering/issues/14)
- [15](https://github.com/litecoin-foundation/litewallet-engineering/issues/15)

It's because somehow SwiftUI is being called on a non-main thread.

### CODE REVIEW

**Review by kcw-grunt — CHANGES_REQUESTED** [review]
Thanks @azisramdhan .
Will you help by adding the issue number into the PR description?  That way we can remember.  GH makes it easy. You just hit `#` you can scroll through the issues.

**Comment by azisramdhan** [comment]
Sure @kcw-grunt I have added into the description.

**Comment by azisramdhan** [comment]
Hi @kcw-grunt I can't add the issue number because it's opened on [litewallet-engineering](https://github.com/litecoin-foundation/litewallet-engineering) I guess

**Review by kcw-grunt — APPROVED** [review]
LGTM

**Comment by azisramdhan** [comment]
Thanks!

**Pull request merged**
