### PR TITLE
 🦺[Tech Debt] removed reference to the unused Circle font

### PR DESCRIPTION
**Pull request by kcw-grunt**
## Why?
There were references to fonts that are not being used.

### CODE REVIEW

**Review by JCHeist — APPROVED** [review]
Love removing dead references :D

**Review by mosadialiou — APPROVED** [review]
LGTM

**Comment by JCHeist** [comment]
This good to merge? @kcw-grunt

**Comment by kcw-grunt** [comment]
> This good to merge? @kcw-grunt
Yeah. I wanted our Turkish work done. In general the author of the PR is responsible to merge and delete the branch.

**Pull request merged**
