### PR TITLE
🥳[Feature] Redesign unlock view

### LINKED ISSUE #7: 🥳 [Feature] Redesign of Login View
##  Overview
The current Login and the Header need to change to reduce confusion for users. Many users mistake the latest Litecoin price with their balance.  Also, some device layouts run out of space and some fiat currencies have multiple decimal places.

## Feature Description
This feature will have to improvements.
* Move the daily price to a obvious location
* Remove the price from the header to give more space for the balance / local fiat value
* Re-layout in the Login View for better UX

## Definition of Done 

- [ ] Re-layout per @antematijaca design

- [ ] Removed price from the header view

### PR DESCRIPTION
**Pull request by kcw-grunt**
## Issue
Closes #7 

## Why?
The current price (in the header view) was confusing many users and the lock screen needed a refresh.

## Screenshots
|Before|**ENG-USD**|**FR-GBP**|**ENG-EUR**|
|-------|------|-------|------|
|LegacyLockScreen|Eng-USD-NewLockScreen|Fra-GBP-NewLockScreen|Eng-EUR-NewLockScreen|

### CODE REVIEW

**Comment by JCHeist** [comment]
On the topic of the lock screen, I have not found a way to set up biometrics to login,  Is that set up and Im missing it or is it something that we should create an issue for? @kcw-grunt 
Hey @JasperHeist  it's in the settings > Security > TouchID/Face ID

**Review by JCHeist — COMMENTED** [review]
I think we should still have somewhere we can show the price after logging in, even if it's just in the menu or something. If you think not, we can push this down to a future redesign. @kcw-grunt 

I do agree that it was confusing having current holdings and price right there though.

**Review by mosadialiou — APPROVED** [review]
LGTM

**Comment by kcw-grunt** [comment]
> I think we should still have somewhere we can show the price after logging in, even if it's just in the menu or something. If you think not, we can push this down to a future redesign. @kcw-grunt
> 
> I do agree that it was confusing having current holdings and price right there though.

Agreed. This was just a `stop the bleeding` fix. Too many people think when they download Litewallet, the balance was on the right and "Where's my money?" " How do I get the $200?" ...I wish I was kidding.

**Pull request merged**
