### PR TITLE
✨[Feature] Add appsflyer

### PR DESCRIPTION
**Pull request by kcw-grunt**
# Overview
Added SDK to more accurately count MAU for both platforms

### CODE REVIEW

**Comment by kcw-grunt** [comment]
cc: @azisramdhan

**Review by josikie — APPROVED** [review]
Thank you! @kcw-grunt 
What is MAU?

**Comment by azisramdhan** [comment]
It stands for Monthly Active Users I guess @josikie

**Review by azisramdhan — APPROVED** [review]

**Comment by kcw-grunt** [comment]
🏆 ! yes @azisramdhan and @josikie  `MAU = Monthly Active Users`.
 As mobile developers, it is the most critical way we measure growth of our apps.

**Pull request merged**
