### PR TITLE
🦺[Tech Debt] Fix env for Litewallet team devs

### PR DESCRIPTION
**Pull request by kcw-grunt**
## Goal
Modify the repo to allow the main iOS devs to sync and collaborate
- @JasperHeist 
- @kcw-grunt 

## Approach
- Review the .gitignore file
- Set the Cocoapods version to `1.10.1`

### CODE REVIEW

**Review by JCHeist — APPROVED** [review]
~It looks good to me. There’s not files it wants to commit now. I can try a fresh install later to check if that has any issues. But the issues that existed before are gone now.~

**Review by JCHeist — CHANGES_REQUESTED** [review]
Actually... I was wrong. I'm going to push the branch of files still not being ignored for me.

**Comment by kcw-grunt** [comment]
> Actually... I was wrong. I'm going to push the branch of files still not being ignored for me.

Ok.
I'll keep eyes on it @JasperHeist

**Comment by kcw-grunt** [comment]
This is was a working branch. Problem fixed.

**Pull request closed without merging**
